            - name: Contract Vulnerability Detection
  # You may pin to the exact commit or the version.
  # uses: outdef/contract-vulnerability-action@2a332156ee911f6534bec02b8a4781413d3a9591
  uses: outdef/contract-vulnerability-action@v0.1.0
  with:
    # Path to run action from. Note that `files`, `target`, `slither-config`, `mythril-contract`,  and `config` are relative to this path
    workdir: # optional
    # Solidity files to analyze
    files: 
    # Contracts to analyze (comma-separated list) by Echidna
    echidna-contract: # optional
    # Config file for echidna (CLI arguments override config options)
    echidna-config: # optional
    # Output format: json, text, none. Disables interactive UI
    format: # optional
    # Directory to store corpus and coverage data
    corpus-dir: # optional
    # Type of tests to be performed
    test-mode: # optional
    # Use multi-abi mode of testing
    multi-abi: # optional
    # Number of sequences of transactions to generate during testing
    test-limit: # optional
    # Number of tries to attempt to shrink a failing sequence of transactions
    shrink-limit: # optional
    # Number of transactions to generate during testing
    seq-len: # optional
    # Address to deploy the contract to test
    contract-addr: # optional
    # Address of the deployer of the contract to test
    deployer: # optional
    # Addresses to use for the transactions sent during testing
    sender: # optional
    # Run with a specific seed
    seed: # optional
    # Additional arguments to use in crytic-compile for the compilation of the contract to test
    crytic-args: # optional
    # Additional arguments to use in solc for the compilation of the contract to test
    solc-args: # optional
    # Version of the Solidity compiler to use
    solc-version: # optional
    # Capture echidna's output into this file. The path must be relative to the repository root.
    output-file: # optional
    # Apply logical NOT to echidna-test's exit status (for testing the action)
    negate-exit-status: # optional
    # Version of the Echidna Docker image to use
    echidna-version: # optional, default is latest
    # The path of the project that Slither should analyze, relative to the repo root.
    target: # optional, default is .
    # If provided, the path of the SARIF file to produce, relative to the repo root.
    sarif: # optional
    # Extra arguments to pass to Slither.
    slither-args: # optional
    # The path to the Slither configuration file. By default, `./slither.config.json` is used if present.
    slither-config: # optional
    # Cause the action to fail if Slither finds any findings of this severity or higher. By default it will fail if any finding is found
    fail-on: # optional, default is all
    # Disable Slither analysis
    disable-slither: # optional
    # The path of the contracts to analyze, relative to the repo root. (comma-separated list)
    mythril-contract: # optional
    # Extra arguments to pass to Mythril.
    mythril-args: # optional
    # 
    internal-github-workspace: # optional, default is ${{ toJSON(github.workspace) }}
          
